name:                Tron
version:             0.1.0.0
github:              De3up/Tron
license:             BSD3
author:              Timofey Gorlov
maintainer:          "example@example.com"
copyright:           2018 Timofey Gorlov

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executable:
  main:                Main.hs
  source-dirs:         app
  ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
  dependencies:
    - Tron
    - gloss

tests:
  Tron-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - Tron
